# 宝塔：放在 include rewrite 之前

location ^~ /aba/ {
    alias /www/wwwroot/baby91.top/aba/;
    index index.html;
}

location = /aba {
    return 301 /aba/;
}

# https://baby91.top/aba/activity/Custom/211/
